[ADD] 전체 상품 필터 기능 구현
wecode-bootcamp-korea/31-2nd-WithMe-backend pull request #10
Opened 2022-04-18 08:22 UTC by leesan195159

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 전체 상품 중에서 원하는 조건대로 필터링 할 수 있도록 구현했다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 필터링
- Q객체를 이용하여 사용자가 원하는 조건대로필 필터링하여 전달할 수 있도록 구현했다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-19 07:12 UTC, bigfanoftim requested changes

2022-04-19 07:12 UTC, bigfanoftim commented on places/views.py
> +            place_list = place_list.order_by('-price')
이걸 이렇게 굳이 나누는 특별한 이유가 없다면 1차 프로젝트때 리뷰 드린것처럼 써서 그대로 활용하면 됩니다. 불필요하게 많은 분기처리가 되어있네요.
```python
sort = request.GET.get('sort', '-created-at')
...objects.filter(...).order_by(sort)
```

2022-04-21 08:56 UTC, leesan195159 commented
테스트 시간이 부족해서 수정하지 못했습니다 ㅠㅠ 주말에 수정해서 올리겠습니다

2022-04-21 09:12 UTC, bigfanoftim requested changes

2022-04-21 09:12 UTC, bigfanoftim commented on places/views.py
> +            return JsonResponse({'message': 'Type error'}, status=200)
```suggestion
            return JsonResponse({'message': 'Key error'}, status=400)
```

2022-04-21 09:12 UTC, bigfanoftim commented on places/views.py
> +            return JsonResponse({'message': 'Type error'}, status=200)
```suggestion
            return JsonResponse({'message': 'Type error'}, status=400)
```

2022-04-21 10:03 UTC, bigfanoftim requested changes

2022-04-21 10:03 UTC, bigfanoftim commented on places/views.py
> +            return JsonResponse({'message': 'Type error'}, status=400)
급한 마음은 잘 알겠지만~ 👀 
```suggestion
            return JsonResponse({'message': 'Key error'}, status=400)
```

2022-04-21 10:05 UTC, leesan195159 commented on places/views.py
> +            return JsonResponse({'message': 'Type error'}, status=200)
......................저는.... 뛰어내려야겠어요... 죄송합니다

2022-04-21 10:12 UTC, leesan195159 commented on places/views.py
> +            return JsonResponse({'message': 'Type error'}, status=400)
......................저는.... 진짜...뛰어내려야겠어요... 죄송합니다 수정 다 했습니다~

2022-04-21 10:27 UTC, bigfanoftim commented on places/views.py
> +            return JsonResponse({'message': 'Type error'}, status=400)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-04-21 10:28 UTC, bigfanoftim approved these changes

2022-04-21 10:28 UTC, merged