[Modify]Mypage -> reservation
wecode-bootcamp-korea/31-2nd-WithMe-backend pull request #17
Opened 2022-04-19 05:14 UTC by JeongHyeon-01

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 예약부분

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. HTTP 요청에 따른 예약정보 호출 및 삭제

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-04-19 07:42 UTC, bigfanoftim requested changes

2022-04-19 07:42 UTC, bigfanoftim commented on cores/decorator.py
> +            request.user = user
```suggestion
            request.user = User.objects.get(id = payload['user_id'])
```

2022-04-19 07:42 UTC, bigfanoftim commented on users/tests.py
>  class KakaoLoginTest(TestCase):
이 클래스는 아래와 무슨 차이가 있는건가요?
```suggestion
class KakaoLoginTest(TestCase):
```

2022-04-19 07:42 UTC, bigfanoftim commented on users/views.py
> +        reservation_queryset = Reservation.objects.select_related('place').filter(user = user.id)
```suggestion
        reservation_queryset = Reservation.objects.select_related('place').filter(user = user)
```

2022-04-19 07:54 UTC, JeongHyeon-01 commented
오타수정해서 재 PR올렸습니다

2022-04-19 08:57 UTC, bigfanoftim requested changes
Conflict 해결까지 해주세요~

2022-04-19 08:57 UTC, bigfanoftim commented on users/views.py
> +        reservation_queryset = Reservation.objects.select_related('place').filter(user = user.id)
👀

2022-04-20 01:12 UTC, bigfanoftim requested changes

2022-04-20 01:12 UTC, bigfanoftim commented on users/views.py
> +        reservation_queryset = Reservation.objects.select_related('place').filter(user = user.id)
```suggestion
        reservation_queryset = Reservation.objects.select_related('place').filter(user = user)
```

2022-04-20 03:03 UTC, JeongHyeon-01 commented
수정사항
1. 기존수정 사항 반영 
2. 현재날짜와 비교하여 이미 지난 예약 이라면 취소가 불가능하게 분기처리

2022-04-20 06:03 UTC, bigfanoftim approved these changes
LGTM 👍

2022-04-20 06:03 UTC, bigfanoftim commented on users/views.py
> +        reservation_queryset = Reservation.objects.select_related('place').filter(user = user.id)
```suggestion
        reservation_queryset = Reservation.objects.select_related('place').filter(user = user)
```

2022-04-20 06:03 UTC, merged