[Add]Signin
wecode-bootcamp-korea/31-2nd-WithMe-backend pull request #3
Opened 2022-04-13 08:22 UTC by JeongHyeon-01

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- OAuth를 통한 로그인 구현 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. Kakao API를 통한 로그인 기능 
- Browser -> Kakao API -> Browser -> Server -> JWT발행 및 Browser에 전달
- 프론트엔드와 통신및 토큰발행 확인 완료

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- OAuth 에 대해서 많이 생각 해본 계기가 되었습니다.

<br />

## :: 기타 질문 및 특이 사항
-

2022-04-13 08:39 UTC, bigfanoftim commented
merge된게 없는데 conflict가 발생했네요!??! 해결 후 다시 푸시해주세요~

2022-04-13 10:52 UTC, JeongHyeon-01 commented
오잉? 일단 해결후 다시 커밋 보냈습니다.

2022-04-13 12:57 UTC, bigfanoftim requested changes

2022-04-13 12:57 UTC, bigfanoftim commented on users/views.py
> +        profile_image = kakao_user['kakao_account']['profile'].get('profile_image_url', None)
다른 부분과는 다르게 이 부분만 따로 변수 지정하신 이유가 있을까요??

2022-04-13 12:57 UTC, bigfanoftim commented on users/views.py
> +        login_user , state = User.objects.get_or_create(
`get_or_create` 메소드 사용 시 생성된 경우에도 생성된 인스턴스가 반환됩니다. 따라서 `login_user`보다는 그냥 `user`로 적어주시는편이 더 좋을 것 같아요!
```suggestion
        user , state = User.objects.get_or_create(
```

2022-04-13 12:57 UTC, bigfanoftim commented on users/views.py
> +        status = 201
```suggestion
        if not state:
            login_user.profile_image = profile_image
            login_user.save()

        status = 200 if not state else 201
```

2022-04-13 12:57 UTC, bigfanoftim commented on users/urls.py
> +from users.views import KaKaoLoginView
```suggestion
from django.urls import path

from users.views import KaKaoLoginView
```

2022-04-13 12:57 UTC, bigfanoftim commented on users/views.py
> +from django.conf         import settings
```suggestion
import jwt, datetime, requests
from json.decoder import JSONDecodeError

from django.views import View
from django.http  import JsonResponse
from django.conf  import settings

from users.models        import User
```

2022-04-13 14:40 UTC, JeongHyeon-01 commented on users/views.py
> +        profile_image = kakao_user['kakao_account']['profile'].get('profile_image_url', None)
아래에 적으면 코드가 너무 길어져서 적어둔것 같습니다 다른부분 과 똑같이 넣어두겠습니다.

2022-04-13 14:41 UTC, JeongHyeon-01 commented on users/views.py
> +        login_user , state = User.objects.get_or_create(
넵!

2022-04-13 14:41 UTC, JeongHyeon-01 commented on users/views.py
> +        status = 201
else를 안쓰려고 적어둔것인데 수정에 반영하겠습니다!

2022-04-14 01:36 UTC, lordmyshepherd requested changes

2022-04-14 01:36 UTC, lordmyshepherd commented on users/views.py
> +                return JsonResponse({'message' : 'Invalid token'}, status=401)
아래와 같이 Kakao API 관련된 로직은 class로 그룹핑할 수 있습니다.  

그렇게 되면 kakao API 관련된 로직은 하나의 class에서 관리하면 된다는 장점이 있고, 만약에 나중에 kakao api 호출부의 수정일 있을 경우 `KakaoLoginView`를 수정할 필요가 없이 `KakaoAPI` 클래스만 수정하면 됩니다. 

결국 Kakao API를 호출하는 위치에서는 Interface만 알고 사용하면 되고 내부적으로 어떻게 구현되었는지 알 필요가 없습니다.

```python
class KakaoAPI:
    def __init__(self, access_token):
        self.access_token = access_token
        self.user_url     = 'https://kapi.kakao.com/v2/user/me'
	self.map_url      = 

    def get_kakao_user(self):
        headers = {"Authorization": f"Bearer ${self.access_token}"}

        response = requests.get(self.user_url, headers=headers)
    
	if not response.status_code == 200:
            return
	
	return response.json()

    def get_location():
        return   

class KakaoLoginView(View):
    def post(self, request):
        try:
            kakao_access_token = request.headers['Authorization']
            kakao_user = KakaoAPI(kakao_access_token)
```

2022-04-14 01:45 UTC, JeongHyeon-01 commented on users/views.py
> +                return JsonResponse({'message' : 'Invalid token'}, status=401)
오! 감사합니다 바로 적용후 PR 올리겠습니다

2022-04-14 04:10 UTC, JeongHyeon-01 commented
kakao.py로 따로 관리 하도록 변경했습니다

2022-04-14 06:28 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-04-14 06:28 UTC, merged